# Generated by Django 3.1.7 on 2021-04-23 06:37

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Program name', max_length=255)),
                ('currency', models.CharField(choices=[('₹', 'INR'), ('$', 'USD'), ('€', 'EURO')], help_text='Currency', max_length=4)),
                ('cost', models.PositiveIntegerField(help_text='Program cost')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(help_text='description')),
                ('program_image', models.ImageField(default='default.jpg', upload_to='fitness')),
                ('slug', models.SlugField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Your first name', max_length=255)),
                ('last_name', models.CharField(help_text='Your last name', max_length=255)),
                ('email', models.EmailField(help_text='Your email address', max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Your mobile number (e.g. +12125552368)', max_length=128, region=None)),
                ('short_message', models.TextField(blank=True, help_text='any short message')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitness.program')),
            ],
        ),
    ]
