# Generated by Django 3.1.7 on 2021-05-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20210429_1442'),
        ('packages', '0003_auto_20210503_1432'),
    ]

    operations = [
    ]
