# Generated by Django 3.1.7 on 2021-04-23 06:37

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Keep your title short upto 255', max_length=255)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('blog_image', models.ImageField(default='default.jpg', help_text='Select background image (Size 450*938)', upload_to='blog_images/')),
                ('seo', models.TextField(blank=True, help_text='SEO')),
                ('tags', models.TextField(blank=True, help_text='Tags')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('activity', models.ManyToManyField(blank=True, help_text='Select related activities', to='packages.Activity')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('continent', models.ForeignKey(blank=True, help_text='Select related continent', null=True, on_delete=django.db.models.deletion.PROTECT, to='packages.continent')),
                ('country', models.ForeignKey(blank=True, help_text='Select related country', null=True, on_delete=django.db.models.deletion.PROTECT, to='packages.country')),
                ('package', models.ForeignKey(blank=True, help_text='Select related package', null=True, on_delete=django.db.models.deletion.PROTECT, to='packages.package')),
                ('region', models.ForeignKey(blank=True, help_text='Select related region', null=True, on_delete=django.db.models.deletion.PROTECT, to='packages.region')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name=())),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='blogs.blog')),
            ],
        ),
        migrations.CreateModel(
            name='SaveBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_saved', models.BooleanField(default=False, verbose_name='Save this blog')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savedblogs', to='blogs.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Reply...')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='blogs.comment')),
            ],
        ),
        migrations.CreateModel(
            name='LikeBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='likes', to='blogs.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
