# Generated by Django 3.1.7 on 2021-05-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.AddField(
            model_name='blog',
            name='keywords',
            field=models.TextField(blank=True, help_text='keywords'),
        ),
    ]
