# Generated by Django 3.1.7 on 2021-05-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20210504_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, help_text='add description here...'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='keywords',
            field=models.TextField(blank=True, help_text='add keywords here...'),
        ),
    ]
