# Generated by Django 3.1.7 on 2021-05-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20210504_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title_tag',
            field=models.CharField(blank=True, help_text='add title tag here...', max_length=255, null=True),
        ),
    ]
