# Generated by Django 3.1.7 on 2021-04-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, help_text='Your DOB (YYYY-MM-DD)'),
        ),
    ]
