# Generated by Django 3.1.7 on 2021-04-23 06:37

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekendAdventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name', max_length=255)),
                ('details', ckeditor.fields.RichTextField(help_text='details')),
                ('image', models.ImageField(default='default.jpg', upload_to='weekend')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeekendAdventureBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Your first name', max_length=255)),
                ('last_name', models.CharField(help_text='Your last name', max_length=255)),
                ('email', models.EmailField(help_text='Your email address', max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Your mobile number (e.g. +12125552368)', max_length=128, region=None)),
                ('short_message', models.TextField(blank=True, help_text='any short message')),
                ('weekend_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='weekend.weekendadventure')),
            ],
        ),
    ]
